from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import numpy as np


VERTEX_DTYPE = np.dtype([
    ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
    ("red", "u1"), ("green", "u1"), ("blue", "u1"),
    ("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4"),
])


@dataclass
class PointCloud:
    points: np.ndarray
    colors: np.ndarray
    normals: np.ndarray
    path: Path

    def transformed(self, transform: np.ndarray) -> "PointCloud":
        rotation, translation = transform[:3, :3], transform[:3, 3]
        return PointCloud(
            self.points @ rotation.T + translation,
            self.colors.copy(),
            self.normals @ rotation.T,
            self.path,
        )


def _header_and_offset(path: Path) -> tuple[str, int]:
    raw = path.read_bytes()
    marker = b"end_header"
    end = raw.index(marker) + len(marker)
    if raw[end:end + 2] == b"\r\n":
        end += 2
    elif raw[end:end + 1] == b"\n":
        end += 1
    else:
        raise ValueError(f"Cabecalho PLY invalido: {path}")
    return raw[:end].decode("ascii"), end


def load_ply(path: str | Path) -> tuple[PointCloud, dict]:
    path = Path(path)
    header, offset = _header_and_offset(path)
    lines = header.splitlines()
    vertex_count = int(next(line.split()[-1] for line in lines if line.startswith("element vertex")))
    face_line = next((line for line in lines if line.startswith("element face")), None)
    face_count = int(face_line.split()[-1]) if face_line else 0
    if "format binary_little_endian 1.0" not in header:
        raise ValueError("Esta implementacao espera PLY binario little-endian.")
    required = ["property float x", "property uchar red", "property float nx"]
    if not all(item in header for item in required):
        raise ValueError("PLY nao contem o esquema xyz/rgb/normais esperado.")
    values = np.fromfile(path, dtype=VERTEX_DTYPE, offset=offset, count=vertex_count)
    points = np.column_stack((values["x"], values["y"], values["z"])).astype(np.float64)
    colors = np.column_stack((values["red"], values["green"], values["blue"])).astype(np.uint8)
    normals = np.column_stack((values["nx"], values["ny"], values["nz"])).astype(np.float64)
    finite = np.isfinite(points).all(axis=1) & np.isfinite(normals).all(axis=1)
    cloud = PointCloud(points[finite], colors[finite], normals[finite], path)
    extent = np.ptp(cloud.points, axis=0)
    info = {
        "file": path.name, "vertices_header": vertex_count, "vertices_valid": len(cloud.points),
        "faces": face_count, "has_colors": True, "has_normals": True,
        "finite_vertices": int(finite.sum()), "invalid_vertices_removed": int((~finite).sum()),
        "unique_vertices": int(len(np.unique(cloud.points, axis=0))),
        "bbox_min": cloud.points.min(axis=0).tolist(), "bbox_max": cloud.points.max(axis=0).tolist(),
        "extent": extent.tolist(), "centroid": cloud.points.mean(axis=0).tolist(),
        "is_triangular_mesh": bool(face_count),
    }
    return cloud, info


def write_ply(path: str | Path, cloud: PointCloud, colors: np.ndarray | None = None) -> None:
    path = Path(path)
    rgb = cloud.colors if colors is None else np.asarray(colors, dtype=np.uint8)
    normals = cloud.normals.copy()
    lengths = np.linalg.norm(normals, axis=1)
    normals[lengths > 0] /= lengths[lengths > 0, None]
    values = np.empty(len(cloud.points), dtype=VERTEX_DTYPE)
    for index, name in enumerate(("x", "y", "z")):
        values[name] = cloud.points[:, index]
        values[("nx", "ny", "nz")[index]] = normals[:, index]
        values[("red", "green", "blue")[index]] = rgb[:, index]
    header = "\n".join([
        "ply", "format binary_little_endian 1.0", "comment Generated by Hackathon Alliage registration pipeline",
        f"element vertex {len(values)}", "property float x", "property float y", "property float z",
        "property uchar red", "property uchar green", "property uchar blue",
        "property float nx", "property float ny", "property float nz", "end_header", "",
    ])
    with path.open("wb") as output:
        output.write(header.encode("ascii"))
        values.tofile(output)
